# Generated by Django 6.1.1 on 2026-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_historicalshiftswaprequest_shiftswaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshift',
            name='ward',
            field=models.CharField(blank=True, help_text='Informational only. Never gates anything, by design.', max_length=100),
        ),
        migrations.AddField(
            model_name='shift',
            name='ward',
            field=models.CharField(blank=True, help_text='Informational only. Never gates anything, by design.', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalshift',
            name='role',
            field=models.CharField(help_text="What the shift needs covering, e.g. 'ENT Registrar'. Compared against Profile.role when someone accepts a swap.", max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='role',
            field=models.CharField(help_text="What the shift needs covering, e.g. 'ENT Registrar'. Compared against Profile.role when someone accepts a swap.", max_length=100),
        ),
    ]
