from django.contrib import admin

from .models import ComplianceAlert


@admin.register(ComplianceAlert)
class ComplianceAlertAdmin(admin.ModelAdmin):
    """No SimpleHistoryAdmin here: an alert is derived state, regenerated by
    the sweep from the profile's licence data. `created_at`/`resolved_at` are
    the whole of its life story, and the licence changes that drive it are
    already in the Profile history."""

    list_display = (
        "profile",
        "facility",
        "alert_type",
        "due_date",
        "status",
        "created_at",
    )
    list_filter = ("status", "alert_type", "profile__facility")
    search_fields = ("profile__full_name", "profile__email", "profile__license_number")
    readonly_fields = ("created_at", "resolved_at")
    date_hierarchy = "due_date"

    @admin.display(description="Facility", ordering="profile__facility__name")
    def facility(self, obj):
        return obj.profile.facility

    def get_queryset(self, request):
        return (
            super()
            .get_queryset(request)
            .select_related("profile", "profile__facility")
        )
