# Generated by Django 6.1.1 on 2026-09-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_pushdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='Drives the compliance sweep. Null means never checked.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='Drives the compliance sweep. Null means never checked.', null=True),
        ),
    ]
