# Generated by Django 6.1.1 on 2026-09-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_historicalprofile_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='role',
            field=models.CharField(blank=True, help_text="Operational designation, e.g. 'ENT Registrar'. Distinct from the licence fields: this is what the facility says someone does, not a credential PSL verifies. Gates shift-swap acceptance — a blank role blocks every swap, deliberately.", max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, help_text="Operational designation, e.g. 'ENT Registrar'. Distinct from the licence fields: this is what the facility says someone does, not a credential PSL verifies. Gates shift-swap acceptance — a blank role blocks every swap, deliberately.", max_length=100),
        ),
    ]
