# Generated by Django 6.1.1 on 2026-09-03 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_historicalprofile_license_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('license_expiring', 'License expiring')], max_length=30)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_alerts', to='profiles.profile')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='alert_status_due_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('profile', 'alert_type'), name='one_open_alert_per_profile_and_type')],
            },
        ),
    ]
